### ISSUE TITLE
支持楼主

### ISSUE THREAD

**Issue by sunchenguang** [wangqingbaidu/bangu#1]
此项目第一个issue，支持，这项目依赖还是比较多的，硬件，软件，等文档全一点。
不知道能不能只选用某几项功能，关闭其他功能，等想上某个功能的时候再打开这样，这样降低上手门槛，由浅入深

**Comment by wangqingbaidu** [comment]
确实是，目前依赖的requets文件存在，还没有将所有的依赖全都添加进去，文档这一块我目前也正在弄，代码里面添加了一些注释，理解起来理论上问题应该不会太大。
功能开关这一块我考虑过，但是后来还是放弃没弄，因为缺少任何一个模块应该不至于程序挂掉，所有县城的开启都放在try块里面了。不过功能开关这一块确实可以弄一下。

**Comment by sunchenguang** [comment]
支持，加油
